// generated automatically by ros_hybrid_protoc on  Sun Feb 19 23:22:53 2023
// Do not Edit!
// wrapping message: std_msgs/Header

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: msgs/std_msgs/Header.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq     uint32                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Stamp   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=stamp,proto3" json:"stamp,omitempty"`
	FrameId string                 `protobuf:"bytes,3,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_std_msgs_Header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_std_msgs_Header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_msgs_std_msgs_Header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Header) GetStamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Stamp
	}
	return nil
}

func (x *Header) GetFrameId() string {
	if x != nil {
		return x.FrameId
	}
	return ""
}

var File_msgs_std_msgs_Header_proto protoreflect.FileDescriptor

var file_msgs_std_msgs_Header_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68, 0x79,
	0x62, 0x72, 0x69, 0x64, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67,
	0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x19, 0x0a, 0x08,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_std_msgs_Header_proto_rawDescOnce sync.Once
	file_msgs_std_msgs_Header_proto_rawDescData = file_msgs_std_msgs_Header_proto_rawDesc
)

func file_msgs_std_msgs_Header_proto_rawDescGZIP() []byte {
	file_msgs_std_msgs_Header_proto_rawDescOnce.Do(func() {
		file_msgs_std_msgs_Header_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_std_msgs_Header_proto_rawDescData)
	})
	return file_msgs_std_msgs_Header_proto_rawDescData
}

var file_msgs_std_msgs_Header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msgs_std_msgs_Header_proto_goTypes = []interface{}{
	(*Header)(nil),                // 0: hybrid.std_msgs.Header
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_msgs_std_msgs_Header_proto_depIdxs = []int32{
	1, // 0: hybrid.std_msgs.Header.stamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msgs_std_msgs_Header_proto_init() }
func file_msgs_std_msgs_Header_proto_init() {
	if File_msgs_std_msgs_Header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgs_std_msgs_Header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_std_msgs_Header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgs_std_msgs_Header_proto_goTypes,
		DependencyIndexes: file_msgs_std_msgs_Header_proto_depIdxs,
		MessageInfos:      file_msgs_std_msgs_Header_proto_msgTypes,
	}.Build()
	File_msgs_std_msgs_Header_proto = out.File
	file_msgs_std_msgs_Header_proto_rawDesc = nil
	file_msgs_std_msgs_Header_proto_goTypes = nil
	file_msgs_std_msgs_Header_proto_depIdxs = nil
}
