// generated automatically by ros_hybrid_protoc on  Sun Feb 19 23:22:54 2023
// Do not Edit!
// wrapping message: std_msgs/MultiArrayLayout

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: msgs/std_msgs/MultiArrayLayout.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiArrayLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dim        []*MultiArrayDimension `protobuf:"bytes,1,rep,name=dim,proto3" json:"dim,omitempty"`
	DataOffset uint32                 `protobuf:"varint,2,opt,name=data_offset,json=dataOffset,proto3" json:"data_offset,omitempty"`
}

func (x *MultiArrayLayout) Reset() {
	*x = MultiArrayLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_std_msgs_MultiArrayLayout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiArrayLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiArrayLayout) ProtoMessage() {}

func (x *MultiArrayLayout) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_std_msgs_MultiArrayLayout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiArrayLayout.ProtoReflect.Descriptor instead.
func (*MultiArrayLayout) Descriptor() ([]byte, []int) {
	return file_msgs_std_msgs_MultiArrayLayout_proto_rawDescGZIP(), []int{0}
}

func (x *MultiArrayLayout) GetDim() []*MultiArrayDimension {
	if x != nil {
		return x.Dim
	}
	return nil
}

func (x *MultiArrayLayout) GetDataOffset() uint32 {
	if x != nil {
		return x.DataOffset
	}
	return 0
}

var File_msgs_std_msgs_MultiArrayLayout_proto protoreflect.FileDescriptor

var file_msgs_std_msgs_MultiArrayLayout_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68, 0x79, 0x62, 0x72, 0x69, 0x64, 0x2e, 0x73,
	0x74, 0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x1a, 0x27, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x73, 0x74,
	0x64, 0x5f, 0x6d, 0x73, 0x67, 0x73, 0x2f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6b, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x72, 0x72, 0x61, 0x79, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x03, 0x64, 0x69, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x68, 0x79, 0x62, 0x72, 0x69, 0x64, 0x2e, 0x73, 0x74, 0x64, 0x5f, 0x6d,
	0x73, 0x67, 0x73, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x64, 0x69, 0x6d, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_std_msgs_MultiArrayLayout_proto_rawDescOnce sync.Once
	file_msgs_std_msgs_MultiArrayLayout_proto_rawDescData = file_msgs_std_msgs_MultiArrayLayout_proto_rawDesc
)

func file_msgs_std_msgs_MultiArrayLayout_proto_rawDescGZIP() []byte {
	file_msgs_std_msgs_MultiArrayLayout_proto_rawDescOnce.Do(func() {
		file_msgs_std_msgs_MultiArrayLayout_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_std_msgs_MultiArrayLayout_proto_rawDescData)
	})
	return file_msgs_std_msgs_MultiArrayLayout_proto_rawDescData
}

var file_msgs_std_msgs_MultiArrayLayout_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msgs_std_msgs_MultiArrayLayout_proto_goTypes = []interface{}{
	(*MultiArrayLayout)(nil),    // 0: hybrid.std_msgs.MultiArrayLayout
	(*MultiArrayDimension)(nil), // 1: hybrid.std_msgs.MultiArrayDimension
}
var file_msgs_std_msgs_MultiArrayLayout_proto_depIdxs = []int32{
	1, // 0: hybrid.std_msgs.MultiArrayLayout.dim:type_name -> hybrid.std_msgs.MultiArrayDimension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msgs_std_msgs_MultiArrayLayout_proto_init() }
func file_msgs_std_msgs_MultiArrayLayout_proto_init() {
	if File_msgs_std_msgs_MultiArrayLayout_proto != nil {
		return
	}
	file_msgs_std_msgs_MultiArrayDimension_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgs_std_msgs_MultiArrayLayout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiArrayLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_std_msgs_MultiArrayLayout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgs_std_msgs_MultiArrayLayout_proto_goTypes,
		DependencyIndexes: file_msgs_std_msgs_MultiArrayLayout_proto_depIdxs,
		MessageInfos:      file_msgs_std_msgs_MultiArrayLayout_proto_msgTypes,
	}.Build()
	File_msgs_std_msgs_MultiArrayLayout_proto = out.File
	file_msgs_std_msgs_MultiArrayLayout_proto_rawDesc = nil
	file_msgs_std_msgs_MultiArrayLayout_proto_goTypes = nil
	file_msgs_std_msgs_MultiArrayLayout_proto_depIdxs = nil
}
